### ISSUE TITLE
Problems with concurrent requests in wai and servant

### ISSUE THREAD

**Issue by rpeszek** [typelead/eta#520]
I am reporting this here because it seems like some of the things I am seeing are probably not wai specific.  Sorry for the length of this ticket, it tires to document various issues I encountered when several requests are executed concurrently/very close to each other by wai Jetty server.

I have a project using servant that now has been converted to eta:
https://github.com/rpeszek/crud-ex-backend-servant/tree/eta-jetty (eta-jetty branch)
It uses Raw WAI logic to serve static files, and I see somewhat different errors with 'true' servant endpoints like endpoints serving JSON.

Right after `etlas run` if I first issue a single GET request like:
http://localhost:9000/static/css/pure.css
everything works fine.  The first request takes some time to complete (warmup time typical of Java apps) but after that everything works and seems fast.

If right after starting the app I point my browser at: http://localhost:9000/elm# (which returns a full page) browser issues 4 GET request one for the page which completes and 3 for CSS and JS file which never complete (none of the 3 completes).  It looks like a deadlock.
If that happens, nothing works until the app is restarted and I issue a simple isolated 'warm-up' request. No errors are printed in the console.

To troubleshoot I added some putStrLn "hello" lines (at the beginning of WAI.Application handler)  to see if the line gets hit.  Weirdly enough, with that change I get errors printed
```
2017-09-17 18:40:09.996:WARN:oejs.HttpChannel:qtp1468343491-15: /static/css/pure.css
eta.runtime.exception.EtaException: thread blocked indefinitely in an MVar operation
	at resourcet.control.monad.trans.Resource$sat_s1FFQ.enter(Resource.hs:189)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at eta.runtime.exception.Exception.catch_(Exception.java:174)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
eta.runtime.exception.EtaException: thread blocked indefinitely in an MVar operation
	at eta.runtime.stg.Capability.detectMVarDeadlock(Capability.java:523)
	at eta.runtime.stg.Capability.idleLoop(Capability.java:516)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:534)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:530)
	at eta.runtime.concurrent.Concurrent.takeMVar(Concurrent.java:63)
	at base.ghc.io.handle.Internals$$wa2.enter(Internals.hs:163)
	at base.ghc.io.handle.Internals$a3_sG1VB.enter(Internals.hs:132)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.ghc.io.handle.Internals$withHandlezq1.enter(Internals.hs:130)
	at base.ghc.io.handle.Internals$wantWritableHandle2.enter(Internals.hs:236)
	at base.ghc.io.handle.Internals$wantWritableHandle1.enter(Internals.hs:226)
	at base.ghc.io.handle.Text$hPutStr2.enter(Text.hs:544)
	at crud_ex_backend_servant.util.WaiStatic$$wa1.enter(WaiStatic.hs:30)
	at crud_ex_backend_servant.util.StaticFiles$sat_s1HO6.enter(StaticFiles.hs:29)
	at eta.runtime.apply.Function.applyPPV(Function.java:164)
	at servant_server.servant.server.Internal$sat_s42PO.enter(Internal.hs:441)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at resourcet.control.monad.trans.Resource$sat_s1FFK.enter(Resource.hs)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.catch_(Exception.java:136)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-09-17 18:40:09.997:WARN:oejs.HttpChannel:qtp1468343491-11: /static/css/styles.css
eta.runtime.exception.EtaException: Exception was thrown in rendering exception of type class java.lang.NullPointerException
	at resourcet.control.monad.trans.Resource$sat_s1FFQ.enter(Resource.hs:189)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at eta.runtime.exception.Exception.catch_(Exception.java:174)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
eta.runtime.exception.EtaException: thread blocked indefinitely in an MVar operation
	at eta.runtime.stg.Capability.detectMVarDeadlock(Capability.java:523)
	at eta.runtime.stg.Capability.idleLoop(Capability.java:516)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:534)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:530)
	at eta.runtime.concurrent.Concurrent.takeMVar(Concurrent.java:63)
	at base.ghc.io.handle.Internals$$wa2.enter(Internals.hs:163)
	at base.ghc.io.handle.Internals$a3_sG1VB.enter(Internals.hs:132)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.ghc.io.handle.Internals$withHandlezq1.enter(Internals.hs:130)
	at base.ghc.io.handle.Internals$wantWritableHandle2.enter(Internals.hs:236)
	at base.ghc.io.handle.Internals$wantWritableHandle1.enter(Internals.hs:226)
	at base.ghc.io.handle.Text$hPutStr2.enter(Text.hs:544)
	at crud_ex_backend_servant.util.WaiStatic$$wa1.enter(WaiStatic.hs:30)
	at crud_ex_backend_servant.util.StaticFiles$sat_s1HO6.enter(StaticFiles.hs:29)
	at eta.runtime.apply.Function.applyPPV(Function.java:164)
	at servant_server.servant.server.Internal$sat_s42PO.enter(Internal.hs:441)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at resourcet.control.monad.trans.Resource$sat_s1FFK.enter(Resource.hs)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.catch_(Exception.java:136)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```
(here pure.css returned 500 and remaining 2 never returned).
I see no errors if putStrLn is removed or if requests are run in isolation. I see the printouts with or without warmup (with warmup fewer printouts and more intermittent).  If requests are run in isolation everything works.  However once the errors are encountered server stops responding and printing anything.  *suggesting that serving threads are dead*.

MemoryManager:
Adding putStrLn to a JSON handler (true Servant endpoint) produces another strange behavior.  No error are printed in JSON request is executed in isolation.
However if it is accompanied with other requests (like CSS files, etc) I get this error:
```
2017-09-17 16:12:02.603:WARN:oejs.HttpChannel:qtp1468343491-16: /things
eta.runtime.exception.EtaException: JException java.lang.IllegalStateException: The block that corresponds to the address 1048587 is not allocated in memory
	at resourcet.control.monad.trans.Resource$sat_s1FFQ.enter(Resource.hs:189)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at eta.runtime.exception.Exception.catch_(Exception.java:174)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by:
java.lang.IllegalStateException: The block that corresponds to the address 1048587 is not allocated in memory
	at eta.runtime.io.MemoryManager.getBoundedBuffer(MemoryManager.java:615)
	at eta.bytestring.Utils.memcmp(Utils.java:46)
	at bytestring.data.bytestring.Internal$$wcompareBytes.enter(Internal.hs:594)
	at http_media.network.http.media.mediatype.Internal$$w$cparseAccept.enter(Internal.hs:47)
	at http_media.network.http.Media$mapAcceptMedia_go.enter(Media.hs:235)
	at http_media.network.http.Media$$w$sparseQuality.enter(Media.hs:232)
	at crud_ex_backend_servant.crudex.Server$$Lr2SVZZ$wlvl18.enter(Server.hs)
	at crud_ex_backend_servant.crudex.Server$$Lr2SW0lvl49.enter(Server.hs)
	at eta.runtime.apply.Function.applyPPP(Function.java:190)
	at servant_server.servant.server.Internal$sat_s40K8.enter(Internal.hs:220)
	at eta.runtime.apply.Function.applyP(Function.java:102)
	at servant_server.servant.server.internal.RoutingApplication$sat_s1X8U.enter(RoutingApplication.hs:379)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at resourcet.control.monad.trans.Resource$sat_s1FFK.enter(Resource.hs)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.catch_(Exception.java:136)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

I sometimes see this super puzzling error that does not even have any of my code in the stack trace:

```
2017-09-17 13:41:33.517:WARN:oejs.HttpChannel:qtp2114537280-11: /things
eta.runtime.exception.EtaException: JException java.nio.BufferUnderflowException
	at resourcet.control.monad.trans.Resource$sat_s1FFQ.enter(Resource.hs:189)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at eta.runtime.exception.Exception.catch_(Exception.java:174)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by:
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:500)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:249)
	at eta.bytestring.Utils.memcmp(Utils.java:50)
	at bytestring.data.bytestring.Internal$$wcompareBytes.enter(Internal.hs:594)
	at http_media.network.http.media.mediatype.Internal$$w$cparseAccept.enter(Internal.hs:47)
	at http_media.network.http.Media$mapAcceptMedia_go.enter(Media.hs:235)
	at http_media.network.http.Media$$w$sparseQuality.enter(Media.hs:232)
	at servant_server.servant.server.Internal$v_s40IY.thunkEnter(Internal.hs:205)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.thunk.Thunk.applyP(Thunk.java:151)
	at servant_server.servant.server.Internal$eta1_s40JA.thunkEnter(Internal.hs)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.thunk.Thunk.applyP(Thunk.java:151)
	at servant_server.servant.server.Internal$sat_s40JM.thunkEnter(Internal.hs)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.apply.Function.applyPV(Function.java:117)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.apply.Function.applyPV(Function.java:117)
	at eta.runtime.apply.Function.applyPPV(Function.java:156)
	at servant_server.servant.server.internal.RoutingApplication$sat_s1X7V.enter(RoutingApplication.hs:215)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyPV(PAP.java:142)
	at eta.runtime.thunk.Thunk.applyPV(Thunk.java:156)
	at servant_server.servant.server.internal.RoutingApplication$sat_s1X8U.enter(RoutingApplication.hs:370)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at resourcet.control.monad.trans.Resource$sat_s1FFK.enter(Resource.hs)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.catch_(Exception.java:136)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

Is putStrLn not safe to use here?
I modified https://github.com/rahulmutt/eta-servant-example code like so:
```
        hello :: Maybe String -> Handler HelloMessage
        hello mname = do
          _ <- liftIO $ putStrLn "Hello"
          return . HelloMessage $ case mname of
             Nothing -> "Hello, anonymous coward"
             Just n  -> "Hello, " ++ n
```

By issuing 2 requests very close to each other right after app start:
http://localhost:9000/invalid
http://localhost:9000/hello

I can get this error:
```
2017-09-17 16:50:31.686:WARN:oejs.HttpChannel:qtp1987360300-10: /hello
eta.runtime.exception.RuntimeInternalError: |[Eta v0.0.9b1] ap_p|Please report this as a bug: https://github.com/typelead/eta/issues
	at eta.runtime.RuntimeLogging.barf(RuntimeLogging.java:15)
	at eta.runtime.stg.Closure.applyP(Closure.java:62)
	at eta.runtime.thunk.Thunk.applyP(Thunk.java:151)
	at main.Main$sat_s3EDC.thunkEnter(Main.hs)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.thunk.Thunk.applyP(Thunk.java:151)
	at bytestring.data.bytestring.builder.Internal$sat_s490T.enter(Internal.hs:391)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.IO$unsafeDupablePerformIO.enter(IO.hs:182)
	at bytestring.data.bytestring.builder.Internal$toLazzyByteStringWith.enter(Internal.hs:248)
	at bytestring.data.bytestring.Builder$toLazzyByteString.enter(Builder.hs:281)
	at main.Main$$s$fAllCTRender_ZC_a_$s$fMimeRender_zt_JSON_a_$cmimeRender2.enter(Main.hs)
	at eta.runtime.apply.Function.applyPP(Function.java:139)
	at servant.servant.api.ContentTypes$bs_s1TVC.thunkEnter(ContentTypes.hs:277)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at servant_server.servant.server.Internal$sat_s40K5.thunkEnter(Internal.hs:189)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at wai.network.Wai$responseLBS1.enter(Wai.hs)
	at servant_server.servant.server.Internal$sat_s40K6.enter(Internal.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyPV(PAP.java:142)
	at blaze_builder.blaze.bytestring.Builder$$wa2_s1GQB.enter(Builder.hs)
	at blaze_builder.blaze.bytestring.Builder$sat_s1GUH.enter(Builder.hs:246)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.IO$unsafeDupablePerformIO.enter(IO.hs:182)
	at blaze_builder.blaze.bytestring.Builder$$wtoLazzyByteStringWith.enter(Builder.hs:245)
	at wai_servlet.network.wai.servlet.Response$$wa.enter(Response.hs:61)
	at wai_servlet.network.wai.servlet.Response$updateHttpServletResponse1.enter(Response.hs)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFE.enter(Jetty.hs:46)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.apply.Function.applyPV(Function.java:117)
	at servant_server.servant.server.internal.RoutingApplication$sat_s1X8U.enter(RoutingApplication.hs:371)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at resourcet.control.monad.trans.Resource$sat_s1FFK.enter(Resource.hs)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.catch_(Exception.java:136)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Hello
```

**Comment by rpeszek** [comment]
I have verified exactly the same code compiling it with stack and the same code (including custom Raw WAI handling and printouts) works correctly, no errors, no locking.

**Comment by rahulmutt** [comment]
Oh this must be the recent change involving deadlock detection. The condition probably needs to be refined. Thanks for reporting this.

**Comment by jneira** [comment]
I am getting the same warnings about not allocated memory buffers with simples requests with eta master version:
```
eta.runtime.exception.EtaException: JException java.lang.IllegalStateException:
The block that corresponds to the address 468 is not allocated in memory
        at eta.runtime.io.MemoryManager.getBoundedBuffer(MemoryManager.java:632)
```

**Comment by jneira** [comment]
Changing the type of allocated buffer to direct seems to make the error gone for me:
https://github.com/jneira/wai-servlet/commit/fb5d29507acfec551ca8dd16023e9ba3500cfc27
I retagged wai-servlet 0.1.1.0 to add the change

**Comment by rahulmutt** [comment]
@jneira Have you run it several more times to confirm that the bug doesn't resurface? Thanks for the information - it will make it easier to trace the culprit!

**Comment by jneira** [comment]
the bug was intermitent but for now it has not been not reproduced since that change

**Comment by rahulmutt** [comment]
Ok thanks. If you manage to construct a smaller example, please do share. All the reproduction cases so far have been long and complex.

**Comment by rpeszek** [comment]
I have just tried 
{code}
etlas install wai-servlet --reinstall --force-reinstalls
{code}
and it reinstalled 0.1.1.0 version but did NOT fix the issue for me.   
I have not done any other updates.

Now, I see completely silent locking most of the time.  No errors are printed, things just deadlock.
However, a very few times I got  "EtaException: thread blocked indefinitely in an MVar operation" printed, so it is not always silent.
Everything works fine if I warm-up the application by making a bunch isolated GET requests first.

**Possibly related**
I also see probably unrelegated intermittent (very rare) ArrayIndexOutOfBoundsExceptions in eta.text.Utils.decode_utf8_int (text package) which seems to be not harmful.
They may indicate some thread safety issues. since I see them printed only when several GET requests hit server concurrently and it happens really very infrequently for me. 

{code}
java.lang.ArrayIndexOutOfBoundsException: 371
	at eta.text.Utils.decode_utf8_int(Utils.java:137)
	at eta.text.Utils.decode_utf8(Utils.java:93)
	at text.data.text.Encoding$$wa2_s49CG.enter(Encoding.hs:135)
	at text.data.text.Encoding$sat_s49EI.enter(Encoding.hs:134)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.ST$runSTRep.enter(ST.hs:164)
	at text.data.text.Encoding$$wdecodeUtf8With.enter(Encoding.hs:132)
	at http_types.network.http.types.URI$sat_sZZT2.thunkEnter(URI.hs:290)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at text.data.text.Show$unpack.enter(Show.hs:42)
	at eta.runtime.apply.Function.applyP(Function.java:102)
	at base.ghc.Base$sat_sAQO.thunkEnter(Base.hs:851)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at filepath.system.filepath.Internal$joinDrive.enter(Internal.hs:646)
	at filepath.system.filepath.Internal$combine.enter(Internal.hs:642)
	at filepath.system.filepath.Internal$joinPath_go.enter(Internal.hs:741)
	at filepath.system.filepath.Internal$joinPath_go.enter(Internal.hs:741)
	at filepath.system.filepath.Internal$joinPath_go.enter(Internal.hs:741)
	at servant_server.servant.utils.StaticFilesWaiPatch$$wa1.enter(StaticFilesWaiPatch.hs)
	at servant_server.servant.utils.StaticFiles$sat_s11WH.enter(StaticFiles.hs:73)
	at eta.runtime.apply.Function.applyPPV(Function.java:164)
	at servant_server.servant.server.Internal$sat_s4KPE.enter(Internal.hs:441)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at resourcet.control.monad.trans.Resource$sat_s1FFK.enter(Resource.hs)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.catch_(Exception.java:136)
	at resourcet.control.monad.trans.Resource$sat_s1FFR.enter(Resource.hs:188)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at resourcet.control.monad.trans.Resource$sat_s1FG4.enter(Resource.hs:187)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs:1067)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Base.hs:1021)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.apply.PAP.applyPPV(PAP.java:174)
	at eta.runtime.thunk.Thunk.applyPPV(Thunk.java:166)
	at wai_cors.network.wai.middleware.Cors$$wa3.enter(Cors.hs:332)
	at crud_ex_backend_servant.crudex.Server$sat_s5KWU.enter(Server.hs:32)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty$sat_sRFP.enter(Jetty.hs:41)
	at eta.runtime.apply.Function.applyO(Function.java:87)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:146)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyO(PAP.java:111)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:156)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.eclipse.jetty.server.handler.AbstractHandler$Eta.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
{code}

I think this error may need a separate ticket.   
It is much harder to reproduce than deadlocks.  I changed the code to print text list passed to joinPath and just making this change seems to prevent me from being able to reproduce ArrayIndexOutOfBoundsException.  Could that be some lazy evaluation issue?

**Comment by rahulmutt** [comment]
@rpeszek Would you be able to do a source installation and run the most recent version of `eta`? I have fixed many concurrent bugs in the process and hopefully some of those bugs should be fixed.

**Comment by rpeszek** [comment]
I updated (eta master branch). I application still deadlocks.  
Trying isolated GET now results in java.lang.OutOfMemoryError in
```
Network.Mime.mimeByExt
```
Here is the error:
```
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at eta.runtime.io.MemoryManager.allocateAnonymousBuffer(MemoryManager.java:287)
	at eta.runtime.io.MemoryManager.allocateBuffer(MemoryManager.java:213)
	at eta.runtime.io.ByteArray.create(ByteArray.java:25)
	at eta.runtime.io.ByteArray.create(ByteArray.java:21)
	at eta.runtime.io.ByteArray.create(ByteArray.java:17)
	at mime_types.network.Mime$$wfileNameExtensions.enter(Mime.hs:56)
	at mime_types.network.Mime$$wmimeByExt.enter(Mime.hs:39)
	at servant_server.servant.utils.StaticFilesWaiPatch$sat_sV10.thunkEnter(StaticFilesWaiPatch.hs:30)
```

**Comment by rahulmutt** [comment]
Thanks for the update. Just to be clear, this is occurring on the `eta-jetty` branch, correct?

**Comment by rpeszek** [comment]
Yes, my project eta-jetty branch

**Comment by rpeszek** [comment]
@rahulmutt
Using my project I just tried this:
```
curl http://localhost:9000/things/0 & curl http://localhost:9000/things/1
```
If I do that right after application starts (etlas run) it makes the application get stuck.
This should be easy to reproduce as this is a simple JSON request, nothing to do with file serving.

If I just do 
```
curl http://localhost:9000/things/0
```
first, then things work and I can do double request safely.

**Comment by jneira** [comment]
For dirscard some possible causes i've done the same test (two simultaneous requests with curl) with the [example app in wai-servlet](https://github.com/jneira/wai-servlet/blob/master/src/Network/Wai/Servlet/Examples.hs#L63) that only shows info about the request and it seems to work fine

**Comment by jneira** [comment]
@rpeszek hi, i am trying to install the project and i get a 
```
[ 1 of 16] Compiling Data.Aeson.Types.Internal ( Data\Aeson\Types\Internal.hs, d
ist\build\Data\Aeson\Types\Internal.jar )

Data\Aeson\Types\Internal.hs:408:17:
    A Template Haskell bracket requires GHC with interpreter support:
      [| Null |]
    Perhaps you are using a stage-1 compiler?
```
Is required some other steps to get it installed? i have eta and etlas installed from source master and i've tried to change the cabal dependencies (restricting aeson to the version in eta-hackage f.e.) with no luck

**Comment by rpeszek** [comment]
@jneira
I have latest eta (master) pulled from yesterday, I assume install.sh installs etlas too. 
```
etlas install --dependencies-only
```
Which installed aeson-1.2.2.0.  aeson-1.2.3.0 is out and is not patched.
Output from yesterday (relevant to aeson) is:
```
Downloading [source] aeson-1.2.2.0...
Building free-4.12.4...
Building wai-cors-0.2.5...
Building attoparsec-iso8601-1.0.0.0...
Found patch in eta-hackage for uri-bytestring-0.3.0.1
Configuring uri-bytestring-0.3.0.1...
Found patch in eta-hackage for aeson-1.2.2.0
Configuring aeson-1.2.2.0...
Building uri-bytestring-0.3.0.1...
Building aeson-1.2.2.0...
Installed attoparsec-iso8601-1.0.0.0
Installed wai-cors-0.2.5
Installed uri-bytestring-0.3.0.1
Found patch in eta-hackage for http-api-data-0.3.7.1
Configuring http-api-data-0.3.7.1...
Building http-api-data-0.3.7.1...
Installed free-4.12.4
Downloading [source] either-4.5...
Configuring adjunctions-4.3...
Configuring either-4.5...
Building adjunctions-4.3...
Building either-4.5...
Installed either-4.5
Installed adjunctions-4.3
Configuring kan-extensions-5.0.2...
Building kan-extensions-5.0.2...
Installed http-api-data-0.3.7.1
Installed kan-extensions-5.0.2
Found patch in eta-hackage for lens-4.15.4
Configuring lens-4.15.4...
Building lens-4.15.4...
Installed lens-4.15.4
Installed aeson-1.2.2.0
```
I was a bit sloppy not setting version boundaries in cabal.  Sorry. 
I guess is a bad habit from using stack.

**Comment by rahulmutt** [comment]
@jneira @Jyothsnasrinivas [recently updated](https://github.com/typelead/etlas-index/commit/4f818553e44b33a54cdaee6bc0f1f00b55777655) `etlas-index` to constrain `etlas`'s dependency solver from not preferring any new versions of patched packages. The fact that you're getting that error is a bug. Can you do a `-v3` and file that as a new issue?

**Comment by jneira** [comment]
Hi, finally i have got it installed with eta d2a05df version

**Comment by rahulmutt** [comment]
@jneira Great. If we can get a tiny code sample that can reproduce this bug, it would be extremely helpful.

**Comment by jneira** [comment]
My previous test was incorrect cause it seems `&` operator in dos run the commands sequentally.
The default wai-servlet-jetty-handler app also hangs doing two parallel request at first, as @rpeszek commented

**Comment by rpeszek** [comment]
If it helps, here is a trivial example:
https://github.com/rpeszek/eta-misc-test/tree/eta-issue-520

All code is in just one file [Main.hs](https://github.com/rpeszek/eta-misc-test/blob/eta-issue-520/src/Main.hs). 
To reproduce do etlas run and as first curl do this:
```
curl http://localhost:9000/foobar/0 & curl http://localhost:9000/foobar/1
```
It was deadlocking reliably on my mac.

**Comment by rahulmutt** [comment]
It turns out the deadlocking is due to a bug in concurrent lazy evaluation of static thunks. Thanks @jneira & @rpeszek for making it easy for me to reproduce it.

**Comment by rahulmutt** [comment]
@jneira @rpeszek I've pushed a fix to master which should fix the deadlocking - can you guys give it a try?

**Comment by rpeszek** [comment]
My simple app 
https://github.com/rpeszek/eta-misc-test/tree/eta-issue-520
works fine

My other app still experiences out of memory error in
```
Network.Mime.mimeByExt
```
as above.  This does not seem to be related to concurrency so form my end it looks like concurrency issue could be fixed.

**Comment by rahulmutt** [comment]
@jneira and @rpeszek - Thanks for the updates! Can you each file separate issues for each unexpected behavior you have observed after the fix?

**Comment by rpeszek** [comment]
@rahulmutt Sure, I will try to reproduce and gather some info. 
 I will try to file the ticket tomorrow.

**Comment by rahulmutt** [comment]
@rpeszek @jneira Just did a binary release for Eta v0.7 which should fix all the weird bugs above. Please test it out and close this issue if it's fixed. You can run `etlas select --latest` to get the new version.
