### ISSUE TITLE
[etlas] Display git-indexed repos accurately

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#634]
`etlas update` currently displays:
```
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
```

It should display this instead:
```
Downloading the latest package lists from:
- hackage.haskell.org
- git@github.com/typelead/etlas-index
```

**Comment by ouromoros** [comment]
I think this issue is already solved? I can see that the name is already updated to etlas.org here
 https://github.com/typelead/etlas/blob/609ab2871b7cfb10226bc6d0ee262cd13966e124/etlas/Distribution/Client/Config.hs#L547

**Comment by rahulmutt** [comment]
@ouromoros Not it is not solved, because the message still doesn't indicate that the source is from a github repository.
